# Generated by Django 6.0.7 on 2026-07-21 09:02

import django.db.models.deletion
import web.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('model_name', models.CharField(max_length=200)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='custom_models/')),
                ('optimizer_name', models.CharField(max_length=200)),
                ('optimizer_params', models.JSONField(blank=True, default=dict)),
                ('metric_names', models.JSONField(default=list)),
                ('primary_metric', models.CharField(blank=True, max_length=100, null=True)),
                ('original_metric', models.CharField(blank=True, max_length=100, null=True)),
                ('seed', models.IntegerField(default=0)),
                ('dataset', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('result', web.fields.SafeJSONField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_trials', models.IntegerField()),
                ('primary_metric', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='web.experiment')),
            ],
        ),
    ]
