# Generated by Django 6.0.7 on 2026-07-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_experiment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='trial_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
