# Generated by Django 6.0.7 on 2026-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_globalsettings_experiment_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='trial_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
