# Generated by Django 6.0.7 on 2026-08-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_run_started_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='stopped_by',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='run',
            name='stopping',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
