# Generated by Django 6.0.7 on 2026-08-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_rename_the_smac_optimizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='run',
            name='optimizer_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='run',
            name='trial_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
