# Generated by Django 6.0.7 on 2026-08-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_run_provenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='optimizer_params',
        ),
    ]
