# Generated by Django 6.0.7 on 2026-08-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0017_experiment_test_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='trial_timeout',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
