# Generated by Django 6.0.7 on 2026-09-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0019_experiment_config_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='backend',
            field=models.CharField(default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='run',
            name='job_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
