# Generated by Django 6.0.7 on 2026-08-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Access permissions',
                'permissions': [('use_custom_models', 'Can upload and run custom models (arbitrary code execution)')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
