# Generated by Django 6.0.7 on 2026-09-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesspermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('use_custom_models', 'Can upload and run custom models (arbitrary code execution)'), ('view_all_experiments', 'Can see every experiment on this instance, not only their own'), ('manage_experiments', "Can run, edit and delete other people's experiments"), ('change_defaults', 'Can change the experiment settings every experiment inherits')], 'verbose_name_plural': 'Access permissions'},
        ),
    ]
