# Generated by Django 6.0.7 on 2026-09-17 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_administrators_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('user_limit', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='accesspermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('use_custom_models', 'Can upload and run custom models (arbitrary code execution)'), ('manage_site', 'Can manage groups, their size and their usage (a site admin)'), ('change_defaults', 'Can change the experiment settings every experiment inherits'), ('view_all_experiments', 'Can see every experiment on the instance, across all groups'), ('manage_experiments', 'Can act on every experiment on the instance, across all groups')], 'verbose_name_plural': 'Access permissions'},
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('lead', 'Group lead')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='access.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group__name', 'user__username'],
            },
        ),
    ]
